import assert from 'node:assert/strict';
import {RunnerGame,STAGES} from './dist/engine.js';
const step=(g,s)=>{for(let t=0;t<s;t+=1/120)g.update(1/120)};
const create=(width=1000)=>{const g=new RunnerGame({width,height:480,random:()=>.5});g.start();g.spawnTime=999;return g;};
let g=create();assert(g.canBoost);assert(g.boost());assert(!g.boost());assert.equal(g.boostEnergy,0);const speed=g.speed;step(g,.5);assert(g.speed>speed);assert(g.speed<=g.maxSpeed);g.obstacles=[{type:'cactus',x:110,y:g.ground-45,w:30,h:45}];step(g,.01);assert.equal(g.state,'running');assert.equal(g.obstacles.length,0);step(g,2.2);assert.equal(g.boostTime,0);assert(g.boostCooldown>0);assert(!g.canBoost);g.boostEnergy=100;assert(!g.boost());step(g,3.1);assert(g.canBoost);assert(g.boost());g.pause();const frozen=[g.elapsed,g.boostTime,g.boostEnergy,g.boostCooldown,g.distance,g.speed];step(g,15);assert.deepEqual([g.elapsed,g.boostTime,g.boostEnergy,g.boostCooldown,g.distance,g.speed],frozen);assert(!g.boost());g.resume();step(g,.1);assert(g.boostTime<frozen[1]);
g.start();assert.equal(g.boostEnergy,100);assert.equal(g.boostTime,0);assert.equal(g.boostCooldown,0);assert.equal(g.stageIndex,0);assert.equal(g.stageBanner,0);assert.equal(g.boosts,0);assert.equal(g.speed,295);
for(let idx=1;idx<=8;idx++){g.distance=idx*600;g.advanceStage();assert.equal(g.stageIndex,idx);assert.equal(g.stage,STAGES[idx%4]);assert.equal(g.obstacles.length,0);assert.equal(g.pickups.length,0);assert.equal(g.stageProgress,0);assert(g.shield>0);assert(g.stageBanner>0);assert(g.boostEnergy<=100);}assert.equal(g.lap,3);
const earth=create(),moon=create();moon.distance=1200;moon.advanceStage();assert(moon.gravity<earth.gravity);earth.jump();moon.jump();step(earth,.8);step(moon,.8);assert.equal(earth.dino.y,earth.ground);assert(moon.dino.y<moon.ground);moon.duck(true);step(moon,.8);assert.equal(moon.dino.y,moon.ground);
for(const width of [600,1000]){g=create(width);g.elapsed=200;g.boost();g.fever=6;step(g,1);assert(g.speed<=g.maxSpeed);g.obstacles=[];g.spawn();const first=g.obstacles[0];assert.equal(g.spawn(),false);first.x-=g.maxSpeed*1.7;assert.equal(g.spawn(),true);assert(g.obstacles[1].x-(first.x+first.w)>=g.maxSpeed*1.62);g.distance=1200;g.advanceStage();g.obstacles=[];g.spawn();const m=g.obstacles[0];m.x-=g.maxSpeed*2.12;assert(g.spawn());assert(g.obstacles[1].x-(m.x+m.w)>=g.maxSpeed*2.05);}
g=create();g.boostEnergy=99;g.collect({x:1,y:1});assert.equal(g.boostEnergy,100);g.boost();for(let i=0;i<10;i++)g.collect({x:1,y:1});assert.equal(g.boostEnergy,0);assert.equal(g.fever,6);g.title();assert.equal(g.state,'ready');assert.equal(g.boostEnergy,100);assert(!g.boost());
console.log('PASS: boost activation, double-trigger rejection, acceleration cap, boost collision immunity, expiry and cooldown, cooldown cannot bypass with energy, recharge, pause freezes every timer, resume, retry resets every mechanic, 8 stage transitions and loop, low-gravity airtime, fastfall, desktop/mobile high-speed spacing, combined fever and boost, title');
