import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {ArcadeAudio} from './dist/audio.js';
import {RunnerGame} from './dist/engine.js';
import * as PrestigeModule from './dist/prestige.js';
import * as Hyper from './dist/hyper.js';
import * as Astral from './dist/astral.js';
import * as Growth from './dist/progression.js';
import * as AdEngine from './dist/ads-engine.js';
const html=readFileSync('./dist/index.html','utf8'),source=readFileSync('./dist/game.js','utf8').replace(/^import .*;$/gm,'');
class Element {constructor(id){this.id=id;this.events={};this.disabled=false;this.dataset={};this.attrs={};this.classList={toggle(){},add(){},remove(){},contains(){return false}};this.style={setProperty(){}};this.hidden=false;}addEventListener(t,fn){(this.events[t]??=[]).push(fn)}dispatch(t,data={}){for(const f of this.events[t]??[])f({preventDefault(){},currentTarget:this,target:this,...data})}setAttribute(k,v){this.attrs[k]=v}getAttribute(k){return this.attrs[k]}closest(){return false}focus(){doc.activeElement=this;}querySelectorAll(){return Object.values(elements).filter(e=>e instanceof Button&&!e.disabled)}setPointerCapture(){}hasPointerCapture(){return false}releasePointerCapture(){}getBoundingClientRect(){return{x:0,y:0,width:1000,height:425}}click(){this.dispatch('click')}}
class Button extends Element{};class Anchor extends Element{};
const elements={};for(const m of html.matchAll(/<([a-z]+)[^>]*id="([^"]+)"/g))elements[m[2]]=m[1]==='button'?new Button(m[2]):new Element(m[2]);
const routes=Array.from({length:4},(_,i)=>{const e=new Element();e.dataset.stage=i;return e});const progress=Object.fromEntries(['.charge-track','.boost-track','.route-track','.arcade','.hyper-panel'].map(s=>[s,new Element()]));
const gradient={addColorStop(){}};const context=new Proxy({createLinearGradient(){return gradient},createRadialGradient(){return gradient},measureText(){return{width:40}}},{get(t,p){return t[p]??(()=>{})},set(t,p,v){t[p]=v;return true}});elements.canvas.getContext=()=>context;elements['ad-canvas'].getContext=()=>context;elements['ad-canvas'].getBoundingClientRect=()=>({x:0,y:0,left:0,top:0,width:1440,height:900});
const win=new Element(),doc=new Element();Object.assign(doc,{body:new Element(),documentElement:new Element(),getElementById(id){assert(elements[id],`missing element ${id}`);return elements[id]},querySelector(s){assert(progress[s],`missing selector ${s}`);return progress[s]},querySelectorAll(){return routes},createElement(){return{width:1230,height:50,getContext:()=>context}}});
let frame;const sandbox={ArcadeAudio,RunnerGame,...AdEngine,...Growth,...Astral,...Hyper,...PrestigeModule,document:doc,window:win,localStorage:{getItem(key){return key===Growth.SAVE_KEY?JSON.stringify({version:4}):null},setItem(){}},matchMedia:()=>({matches:false}),HTMLButtonElement:Button,HTMLAnchorElement:Anchor,Image:class{set src(v){this.width=1536;this.height=1024}},ResizeObserver:class{constructor(fn){this.fn=fn}observe(){this.fn()}},devicePixelRatio:1,requestAnimationFrame(fn){frame=fn;return 1},cancelAnimationFrame(){},Set,setTimeout(){},clearTimeout(){},console,Math};sandbox.AdRenderer=class {constructor(canvas){this.canvas=canvas;this.scale=1;this.ox=0;this.oy=0;}resize(){}render(){}stop(){}world(x,y){return {x,z:y}}p(x,z){return{x,y:z}}};vm.createContext(sandbox);for(const [name,exports] of [['prestige-ui','paintPrestige'],['hyper-ui','paintHyper'],['astral-ui','paintAstral'],['progression-ui','paintProgression'],['ads','PlayableAds']])vm.runInContext('(function(){'+readFileSync('./dist/'+name+'.js','utf8').replace(/^import .*;$/gm,'').replace(/export /g,'')+';Object.assign(globalThis,{'+exports+'});})();',sandbox);vm.runInContext(source,sandbox);const get=e=>vm.runInContext(e,sandbox);const key=(code,repeat=false)=>win.dispatch('keydown',{code,repeat,target:elements.canvas});
assert.equal(get('game.state'),'ready');elements.start.click();assert.equal(get('game.state'),'running');key('ShiftLeft');assert(get('game.boostTime')>0);const boostCount=get('game.boosts');key('ShiftLeft',true);assert.equal(get('game.boosts'),boostCount);key('Space');assert.equal(get('game.dino.jumps'),1);key('ArrowUp');assert.equal(get('game.dino.jumps'),2);key('KeyP');assert.equal(get('game.state'),'paused');key('Space');assert.equal(get('game.state'),'running');elements.duck.dispatch('pointerdown',{pointerId:1});assert(get('game.dino.duck'));elements.duck.dispatch('pointercancel');assert(!get('game.dino.duck'));win.dispatch('blur');assert.equal(get('game.state'),'paused');elements.resume.click();get('game.boostTime=0;game.boostCooldown=0;game.boostEnergy=100');elements.boost.click();assert.equal(get('game.boosts'),boostCount+1);elements.motion.click();assert(get('lowMotion'));get("burst(50,50,'rainbow',500);ring(50,50)");assert.equal(get('particles.length'),0);assert.equal(get('rings.length'),0);elements.motion.click();get("burst(50,50,'rainbow',500)");assert.equal(get('particles.length'),260);
get('game.distance=1200;game.advanceStage();hud();render()');assert.equal(elements['zone-name'].textContent,'03 / LUNAR ORBIT');assert(elements['physics-hint'].textContent.includes('低重力'));assert.equal(elements['stage-title'].textContent,'LUNAR ORBIT');elements.back.click();assert.equal(get('game.state'),'ready');assert.equal(get('game.boostEnergy'),100);elements.jump.dispatch('pointerdown');assert.equal(get('game.state'),'running');elements.jump.dispatch('pointerdown');assert.equal(get('game.dino.jumps'),1);elements.jump.dispatch('click',{detail:0});assert.equal(get('game.dino.jumps'),2);frame(1000);frame(1016);assert.equal(typeof elements.score.textContent,'string');
console.log('PASS: UI module boot, all DOM IDs, start, Shift/X boost binding, repeat guard, double jump keys, pause/resume, duck pointer cancel, blur pause, touch boost, reduced-motion particle suppression, particle cap, space-stage HUD/render, retry/title, touch jump and keyboard button activation. DOM/canvas are stubs; this is not browser visual QA.');

get("game.state='over';showOverlay('over')");assert(!elements.revive.hidden);elements.revive.click();assert.equal(get('game.state'),'ad');assert(get('ads.active'));assert(!elements['ad-screen'].hidden);assert(progress['.arcade'].inert);assert(elements['ad-skip'].disabled);const frozenAd=get('[game.score,game.distance,game.elapsed,game.boostEnergy].join()');key('Space');key('ShiftLeft');key('KeyP');get('game.update(.02)');assert.equal(get('[game.score,game.distance,game.elapsed,game.boostEnergy].join()'),frozenAd);assert.equal(get('ads.finish()'),false);get('ads.session.update(4.99);ads.paint()');assert(elements['ad-skip'].disabled);get('ads.session.update(.02);ads.paint()');assert(!elements['ad-skip'].disabled);get('ads.session.update(100);ads.paint()');assert(get('ads.active'));assert.equal(get('game.state'),'ad');const oldKind=get('ads.session.kind');win.dispatch('blur');const elapsed=get('ads.session.elapsed');get('ads.frame(10000);ads.frame(16000)');assert.equal(get('ads.session.elapsed'),elapsed);win.dispatch('focus');get('ads.frame(17000);ads.frame(17016)');assert(get('ads.session.elapsed')>elapsed);elements['ad-skip'].click();assert(!get('ads.active'));assert(elements['ad-screen'].hidden);assert(!progress['.arcade'].inert);assert.equal(get('game.state'),'running');assert.equal(get('game.revivesUsed'),1);assert.equal(get('game.shield'),3);assert.equal(get('ads.finish()'),false);get("game.state='over';showOverlay('over')");assert(!elements.revive.hidden);elements.revive.click();assert(get('ads.active'));assert(elements['ad-skip'].disabled);get('ads.session.update(5);ads.paint()');elements['ad-skip'].click();assert.equal(get('game.revivesUsed'),2);const secondKind=get('ads.order.last');elements.retry.click();assert.equal(get('game.revivesUsed'),0);get("game.state='over';showOverlay('over')");elements.revive.click();assert.notEqual(get('ads.order.last'),secondKind);elements['ad-restart'].click();assert(!get('ads.active'));assert.equal(get('game.state'),'running');assert.equal(get('game.score'),0);assert.equal(get('game.revivesUsed'),0);
console.log('PASS: fake-ad UI entry, background input/world freeze, early-skip guard, 5-second unlock, indefinite play, blur pauses clock, focus restarts clock, repeat revival, safe shield, dialog cleanup, no adjacent repeat, no-ad restart');

get("game.state='over';showOverlay('over')");elements.revive.click();const adElapsed=get('ads.session.elapsed');win.dispatch('resize');assert.equal(get('ads.session.elapsed'),adElapsed);get("ads.session=new AdSession('snow');ads.renderer.resize()");const pick=get('JSON.stringify({x:ads.renderer.ox+ads.renderer.p(-3.8,1).x*ads.renderer.scale,y:ads.renderer.oy+ads.renderer.p(-3.8,1).y*ads.renderer.scale})');const point=JSON.parse(pick);elements['ad-canvas'].dispatch('pointerdown',{pointerId:8,clientX:point.x,clientY:point.y});assert(Math.abs(get('ads.session.model.player.target.x')+3.8)<.01);assert(Math.abs(get('ads.session.model.player.target.z')-1)<.01);elements['ad-canvas'].dispatch('pointercancel');assert.equal(get('ads.pointer'),null);get("ads.session=new AdSession('helix')");elements['ad-canvas'].dispatch('pointerdown',{pointerId:10,clientX:300,clientY:300});elements['ad-canvas'].dispatch('pointermove',{pointerId:10,clientX:350,clientY:300});assert(get('ads.session.model.rotation')<0);elements['ad-canvas'].dispatch('pointerup');assert.equal(get('ads.pointer'),null);key('ArrowLeft');assert(get("ads.session.model.keys.has('ArrowLeft')"));win.dispatch('keyup',{code:'ArrowLeft'});assert(!get("ads.session.model.keys.has('ArrowLeft')"));doc.hidden=true;doc.dispatch('visibilitychange');const hiddenElapsed=get('ads.session.elapsed');get('ads.frame(20000);ads.frame(30000)');assert.equal(get('ads.session.elapsed'),hiddenElapsed);doc.hidden=false;doc.dispatch('visibilitychange');get('ads.stop()');assert(!get('ads.active'));console.log('PASS: active-ad resize preserves progress, renderer-delegated pointer targeting, pointer cancel/up cleanup, helix drag and keyboard, hidden-document timer pause');

// The runner and every intermission share one master and soundtrack owner.
get('game.start()');assert.equal(get('audio.game'),'dino');get('game.pause()');assert.equal(get('audio.game'),null);elements.resume.click();assert.equal(get('audio.game'),'dino');
assert.equal(get('sound'),false);elements.sound.click();assert(get('audio.enabled'));assert.equal(elements['ad-sound'].attrs['aria-pressed'],'true');
get("game.state='over';showOverlay('over')");elements.revive.click();assert.equal(get('audio.game'),get('ads.session.kind'));assert(get('ads.audio===audio'));
key('KeyM');assert(!get('sound'));assert(!get('audio.enabled'));assert.equal(elements.sound.attrs['aria-pressed'],'false');assert.equal(elements['ad-sound'].attrs['aria-pressed'],'false');
elements['ad-sound'].click();assert(get('sound'));assert.equal(elements.sound.attrs['aria-pressed'],'true');assert.equal(elements['ad-sound'].attrs['aria-pressed'],'true');
win.dispatch('blur');assert(!get('audio.foreground'));win.dispatch('focus');assert(get('audio.foreground'));doc.hidden=true;doc.dispatch('visibilitychange');assert(!get('audio.foreground'));doc.hidden=false;doc.dispatch('visibilitychange');assert(get('audio.foreground'));
get('ads.session.update(5);ads.finish()');assert.equal(get('audio.game'),'dino');elements.back.click();assert.equal(get('audio.game'),null);
console.log('PASS: one audio owner across runner/ad/return; pause/title stop music; main and ad mute icons stay synchronized; M works inside the modal; focus/visibility pause shared audio.');

// A finished round is settled exactly once, frozen, and explicitly replayable.
get("game.state='over';game.beginAd();ads.start('snow');ads.session.model.delivered=18;ads.paint()");assert(!elements['ad-result'].hidden);assert.equal(elements['ad-result-title'].textContent,'CLEAR!');assert.equal(get('progression.state.resources.snow'),8);assert.equal(get('game.upgrades.snow'),1);assert(elements['ad-reward-amount'].textContent.includes('+8'));const resultTime=get('ads.session.model.time');get('ads.session.update(.05);ads.paint();ads.paint()');assert.equal(get('ads.session.model.time'),resultTime);assert.equal(get('progression.state.resources.snow'),8);key('ArrowRight');assert.equal(get('ads.session.model.keys.size'),0);assert.equal(get('ads.finish()'),false);elements['ad-replay'].click();assert(elements['ad-result'].hidden);assert.equal(get('ads.session.kind'),'snow');assert.equal(get('ads.session.model.delivered'),0);assert.equal(get('ads.replay()'),false);get('ads.session.elapsed=5;ads.session.roundTime=75;ads.paint()');assert.equal(elements['ad-result-title'].textContent,'TRY AGAIN');assert(elements['ad-reward-amount'].textContent.includes('+0'));elements['ad-return'].click();assert.equal(get('game.state'),'running');assert(!get('ads.active'));assert.equal(get('progression.state.resources.snow'),8);assert(elements['skill-grid'].innerHTML.includes('炉心チャージ'));assert(elements['skill-grid'].innerHTML.includes('NEON RANGE'),'all ten working games appear in the lab');
get('game.title()');elements['skill-grid'].dispatch('click',{target:{closest:()=>({dataset:{play:'stack'}})}});assert(get('ads.active'));assert.equal(get('ads.session.kind'),'stack');assert.equal(get('game.state'),'ready');get('ads.session.elapsed=5;ads.finish()');assert.equal(get('game.state'),'ready');get('game.start()');elements['skill-grid'].dispatch('click',{target:{closest:()=>({dataset:{play:'golf'}})}});assert.equal(get('game.state'),'paused');get('ads.session.elapsed=5;ads.finish()');assert.equal(get('game.state'),'running');
console.log('PASS: success/failure result UI, exact-once material settlement, runner skills applied immediately, frozen input, replay/return guards, zero idle reward, skill collection and direct arcade launch preserve ready/running runner state.');

// The astronomical economy is functional: real production, cost deduction,
// true scaled run totals and persisted best; paused/hidden time cannot farm.
get('game.title();progression.economy.tick(.25,{active:true});paintAstral(progression.economy)');const walletBefore=get('progression.economy.currency.toString()');for(let i=0;i<20;i++)get('progression.economy.tick(.25,{active:true})');get('paintAstral(progression.economy)');assert(get('progression.economy.currency.gt('+JSON.stringify(walletBefore)+')'));assert(!elements['astral-buy-generator'].disabled);const powerBefore=get('progression.economy.power.toString()');elements['astral-buy-generator'].click();assert.equal(get('progression.economy.levels.generator'),1);assert(get('progression.economy.power.gt('+JSON.stringify(powerBefore)+')'));assert(elements['astral-buy-generator'].disabled,'post-buy cooldown blocks repeated clicks');elements['astral-buy-generator'].click();assert.equal(get('progression.economy.levels.generator'),1);get('game.start();game.collect({x:100,y:100});hud()');assert(get('astralRun.gt(game.score)'));const earned=get('astralRun.toString()');get("game.state='over';event({type:'over'})");assert(get('progression.economy.best.eq('+JSON.stringify(earned)+')'));assert.equal(elements['final-score'].textContent,get('formatAstral(astralRun)'));assert(!elements['astral-power'].textContent.includes('Infinity'));assert(!elements['astral-wallet'].textContent.includes('NaN'));get('game.start();game.pause()');const pausedWallet=get('progression.economy.currency.toString()');get('frame(70000);frame(71000)');assert.equal(get('progression.economy.currency.toString()'),pausedWallet);get('game.title()');doc.hidden=true;const hiddenWallet=get('progression.economy.currency.toString()');get('frame(72000);frame(90000)');assert.equal(get('progression.economy.currency.toString()'),hiddenWallet);doc.hidden=false;
console.log('PASS: astronomical reactor production, affordable purchase/deduction, repeat guard, real huge run score+best, finite display and pause/hidden income exclusion.');
get('game.start();game.pause();ads.start("pins")');const duringAd=get('progression.economy.currency.toString()');get('frame(100000);frame(100050)');assert(get('progression.economy.currency.gt('+JSON.stringify(duringAd)+')'),'foreground minigame earns production even if runner was paused');get('ads.stop()');console.log('PASS: foreground mini-game production remains active while its background runner is paused.');
// High-arrow ascension is active and separate from the approximate wallet.
get('game.title();cancelBurst()');const fuel0=get('progression.hyper.fuel');elements['hyper-burst'].dispatch('pointerdown',{pointerId:91});assert(get('progression.hyper.fuel')>fuel0);const pressedFuel=get('progression.hyper.fuel');get('frame(110000);frame(110050);frame(110100);frame(110150);frame(110200);frame(110250)');assert(get('progression.hyper.fuel')>pressedFuel,'held burst gives bounded active pulses');elements['hyper-burst'].dispatch('pointercancel');const releaseFuel=get('progression.hyper.fuel');get('frame(111000);frame(111050);frame(111100);frame(111150);frame(111200)');assert.equal(get('progression.hyper.fuel'),releaseFuel,'no idle fuel after release');for(let i=0;i<6;i++)elements['hyper-burst'].dispatch('click',{detail:0});get('paintHyper(progression.hyper)');assert(!elements['hyper-buy-advance'].disabled);const rank0=get('progression.hyper.rank'),power0=get('progression.economy.power.toString()'),cost0=get('progression.hyper.offer("advance").cost'),beforeBuy=get('progression.hyper.fuel');elements['hyper-buy-advance'].click();assert.equal(get('progression.hyper.rank'),rank0+1);assert.equal(get('progression.hyper.fuel'),beforeBuy-cost0);assert(get('progression.economy.power.gt('+JSON.stringify(power0)+')'),'symbolic prestige has real numerical economy integration');assert(elements['hyper-value'].textContent.includes('10^68'));assert.equal(get('progression.state.hyper.rank'),rank0+1);elements['hyper-burst'].dispatch('pointerdown',{pointerId:92});win.dispatch('blur');assert.equal(get('burstPointer'),null);const blurFuel=get('progression.hyper.fuel');get('frame(115000);frame(115100)');assert.equal(get('progression.hyper.fuel'),blurFuel);win.dispatch('focus');console.log('PASS: deliberate held burst, pointer cancellation, zero idle fuel, exact fuel costs, symbolic ascension, persistent rank and actual reactor power integration.');
// Complete the actual engine's four boundaries, then preview/cancel/confirm.
get('game.start();for(let i=1;i<=4;i++){game.distance=i*600;game.advanceStage();}hud()');assert(get('progression.prestige.canRebirth'));assert.equal(get('progression.prestige.rebirthCount'),0);elements['prestige-open'].click();assert(get('treeOpen'));assert.equal(get('game.state'),'paused');assert(progress['.arcade'].inert);assert(!elements['prestige-screen'].hidden);elements['rebirth-preview'].click();assert(!elements['rebirth-confirmation'].hidden);const beforeCancel=get('progression.economy.currency.toString()');elements['rebirth-cancel'].click();assert(elements['rebirth-confirmation'].hidden);assert.equal(get('progression.economy.currency.toString()'),beforeCancel);assert.equal(get('progression.prestige.rebirthCount'),0);elements['rebirth-preview'].click();elements['rebirth-confirm'].click();assert(get('treeOpen'));assert.equal(get('game.state'),'ready');assert.equal(get('game.distance'),0);assert.equal(get('progression.prestige.rebirthCount'),1);assert.equal(get('progression.prestige.currency'),1);assert.equal(get('progression.economy.currency.toNumber()'),0);elements['rebirth-confirm'].click();assert.equal(get('progression.prestige.rebirthCount'),1);elements['prestige-open'].click();const treeOffer=JSON.parse(get('JSON.stringify(progression.prestige.offerNode("runner_charge"))'));elements['prestige-tree'].dispatch('click',{target:{closest:()=>({dataset:{treeNode:'runner_charge',treeToken:treeOffer.token}})}});assert.equal(get('progression.prestige.currency'),0);assert.equal(get('progression.prestige.ranks.runner_charge'),1);assert(get('game.meta.rechargeMultiplier')>1);elements['prestige-tree'].dispatch('click',{target:{closest:()=>({dataset:{treeNode:'runner_charge',treeToken:treeOffer.token}})}});assert.equal(get('progression.prestige.ranks.runner_charge'),1);elements['prestige-run'].click();assert.equal(get('game.state'),'running');assert(!get('treeOpen'));assert(!progress['.arcade'].inert);console.log('PASS: four-stage UI eligibility, connected tree modal, pause/inert isolation, preview/cancel, voluntary exact-once reset, retained records, tokenized node purchase and immediate runner effect.');

// The live result announcement must use the same huge score shown on screen.
const previousTimeout=sandbox.setTimeout;sandbox.setTimeout=fn=>{fn();return 1};get("game.state='over';game.score=64;lastNumericScore=64;astralRun=new Decimal('ee20');event({type:'over'})");assert.equal(elements.announcement.textContent,`ゲーム終了。スコア ${elements['final-score'].textContent}、最大コンボ ${get('game.maxCombo')}`);sandbox.setTimeout=previousTimeout;
console.log('PASS: accessibility result announcement matches the visible astronomical score instead of the base score.');
