import assert from 'node:assert/strict';
import {RunnerGame} from './dist/engine.js';
import {AdSession,SnowCamp,HoleCity,HelixTower} from './dist/ads-engine.js';
const step=(m,t)=>{for(let e=0;e<t;e+=.01)m.update(.01)};
for(const k of ['snow','hole','helix']){let s=new AdSession(k);assert(!s.close());s.update(2,false);assert.equal(s.elapsed,0);s.update(4.999);assert(!s.ready);assert(!s.close());s.update(.0011);assert(s.ready);step(s,600);assert(s.ready);assert(!s.closed);assert(s.model.time>0);assert(s.close());assert(!s.close());const t=s.elapsed;s.update(3);assert.equal(s.elapsed,t);}
let m=new SnowCamp();m.point(-3.8,1);step(m,3);assert.equal(m.wood,6);const h=m.heat;m.point(0,0);step(m,2);assert.equal(m.wood,0);assert.equal(m.delivered,6);assert(m.heat>h);assert.equal(m.level,2);assert.equal(m.warm,8);m.keys.add('ArrowRight');const x=m.player.x;step(m,.3);assert(m.player.x>x);m.keys.clear();step(m,60);assert(m.heat>=4);
m=new HoleCity();for(const o of m.items.filter(o=>o.size<.65)){m.player.x=o.x;m.player.z=o.z;step(m,.5);}assert(m.eaten>10);assert(m.radius>1.35);const b=m.items.find(o=>o.type==='building');m.player.x=b.x;m.player.z=b.z;step(m,.5);assert(b.eaten);const score=m.score;m.items.forEach(o=>o.eaten=true);step(m,.02);assert(m.items.some(o=>!o.eaten));assert.equal(m.score,score);
m=new HelixTower();m.rotation=Math.PI/2-m.ring().gap-.5;m.ball=0;m.velocity=1;step(m,.01);assert.equal(m.depth,1);assert.equal(m.score,10);m.rotation=Math.PI/2-m.ring().red-.15;m.ball=0;m.velocity=1;step(m,.01);assert.equal(m.hits,1);assert.equal(m.depth,1);assert(m.dead>0);step(m,.7);assert.equal(m.floor,0);assert.equal(m.dead,0);const rot=m.rotation;m.drag(50);assert(m.rotation>rot);m.keys.add('ArrowLeft');step(m,.1);assert(m.rotation<rot+.6);for(let i=0;i<120;i++){m.rotation=Math.PI/2-m.ring().gap-.8;m.ball=0;m.velocity=1;m.update(.01)}assert(m.depth>100);assert(m.score>900);
let g=new RunnerGame();g.start();assert(!g.beginAd());g.score=532;g.coins=17;g.distance=1350;g.stageIndex=2;g.combo=8;g.maxCombo=11;g.elapsed=35;g.boostEnergy=54;g.state='over';const saved=[g.score,g.coins,g.distance,g.stageIndex,g.combo,g.maxCombo,g.elapsed,g.boostEnergy];assert(g.beginAd());assert(!g.beginAd());step(g,10);assert.deepEqual([g.score,g.coins,g.distance,g.stageIndex,g.combo,g.maxCombo,g.elapsed,g.boostEnergy],saved);g.obstacles=[{x:100,y:g.ground-50,w:50,h:50}];assert(g.revive());assert.equal(g.state,'running');assert.deepEqual([g.score,g.coins,g.distance,g.stageIndex,g.combo,g.maxCombo,g.elapsed,g.boostEnergy],saved);assert.equal(g.obstacles.length,0);assert.equal(g.shield,3);assert.equal(g.revivesUsed,1);assert(!g.revive());g.obstacles=[{x:110,y:g.ground-50,w:50,h:50}];g.update(.01);assert.equal(g.state,'running');g.state='over';assert(g.beginAd());assert(g.revive());assert.equal(g.revivesUsed,2);g.start();assert.equal(g.revivesUsed,0);g.state='over';assert(g.beginAd());g.title();assert.equal(g.state,'ready');assert.equal(g.revivesUsed,0);
console.log('PASS: all three models interact and loop; exact 5-second unlock; 10-minute continued play; closed-session guard; snow collection/delivery/heat/keyboard; hole growth/car/building/swallow/reset; helix rotate/gap/red/bounce/120 floors; run state frozen and preserved, repeat revival, 3-second collision safety, restart reset');
